import { copyFileSync, mkdirSync, existsSync } from 'fs'
import { resolve } from 'path'

// Ensure dist/css directory exists
const cssDir = resolve(process.cwd(), 'dist/css')
if (!existsSync(cssDir)) {
  mkdirSync(cssDir, { recursive: true })
}

// Copy CSS file
try {
  copyFileSync(
    resolve(process.cwd(), 'css/juicebox.css'),
    resolve(cssDir, 'juicebox.css')
  )
  console.log('✓ Copied juicebox.css')
} catch (error) {
  console.log('⚠ CSS file not found, will be generated by Vite')
}

// Copy CSS images
const imgDir = resolve(cssDir, 'img')
if (!existsSync(imgDir)) {
  mkdirSync(imgDir, { recursive: true })
}

try {
  copyFileSync(
    resolve(process.cwd(), 'css/img/circular-arrows-24-blue.png'),
    resolve(imgDir, 'circular-arrows-24-blue.png')
  )
  copyFileSync(
    resolve(process.cwd(), 'css/img/circular-arrows-24-grey.png'),
    resolve(imgDir, 'circular-arrows-24-grey.png')
  )
  copyFileSync(
    resolve(process.cwd(), 'css/img/matrix-diagonal-all.svg'),
    resolve(imgDir, 'matrix-diagonal-all.svg')
  )
  copyFileSync(
    resolve(process.cwd(), 'css/img/matrix-diagonal-lower.svg'),
    resolve(imgDir, 'matrix-diagonal-lower.svg')
  )
  copyFileSync(
    resolve(process.cwd(), 'css/img/matrix-diagonal-upper.svg'),
    resolve(imgDir, 'matrix-diagonal-upper.svg')
  )
  console.log('✓ Copied CSS images')
} catch (error) {
  console.log('⚠ CSS images not found')
}

console.log('Asset copying complete!')
